package models

// AgentType represents a agent_type
type AgentType string

// AgentType values
const (
	AgentTypeAGENTTYPEUNSPECIFIED      AgentType = "AGENT_TYPE_UNSPECIFIED"
	AgentTypeAGENTTYPEUNDERWRITING               = "AGENT_TYPE_UNDERWRITING"
	AgentTypeAGENTTYPECLAIMSASSESSOR             = "AGENT_TYPE_CLAIMS_ASSESSOR"
	AgentTypeAGENTTYPEFRAUDDETECTOR              = "AGENT_TYPE_FRAUD_DETECTOR"
	AgentTypeAGENTTYPECUSTOMERSUPPORT            = "AGENT_TYPE_CUSTOMER_SUPPORT"
	AgentTypeAGENTTYPEPOLICYADVISOR              = "AGENT_TYPE_POLICY_ADVISOR"
	AgentTypeAGENTTYPEDOCUMENTANALYZER           = "AGENT_TYPE_DOCUMENT_ANALYZER"
)
