package models

// ClaimType represents a claim_type
type ClaimType string

// ClaimType values
const (
	ClaimTypeCLAIMTYPEUNSPECIFIED           ClaimType = "CLAIM_TYPE_UNSPECIFIED"
	ClaimTypeCLAIMTYPEHEALTHHOSPITALIZATION           = "CLAIM_TYPE_HEALTH_HOSPITALIZATION"
	ClaimTypeCLAIMTYPEHEALTHSURGERY                   = "CLAIM_TYPE_HEALTH_SURGERY"
	ClaimTypeCLAIMTYPEMOTORACCIDENT                   = "CLAIM_TYPE_MOTOR_ACCIDENT"
	ClaimTypeCLAIMTYPEMOTORTHEFT                      = "CLAIM_TYPE_MOTOR_THEFT"
	ClaimTypeCLAIMTYPETRAVELMEDICAL                   = "CLAIM_TYPE_TRAVEL_MEDICAL"
	ClaimTypeCLAIMTYPETRAVELBAGGAGELOSS               = "CLAIM_TYPE_TRAVEL_BAGGAGE_LOSS"
	ClaimTypeCLAIMTYPEDEVICEDAMAGE                    = "CLAIM_TYPE_DEVICE_DAMAGE"
	ClaimTypeCLAIMTYPEDEVICETHEFT                     = "CLAIM_TYPE_DEVICE_THEFT"
	ClaimTypeCLAIMTYPEDEATH                           = "CLAIM_TYPE_DEATH"
)
