package models

// DataCategory represents a data_category
type DataCategory string

// DataCategory values
const (
	DataCategoryDATACATEGORYUNSPECIFIED               DataCategory = "DATA_CATEGORY_UNSPECIFIED"
	DataCategoryDATACATEGORYPERSONALIDENTIFIER                     = "DATA_CATEGORY_PERSONAL_IDENTIFIER"
	DataCategoryDATACATEGORYCONTACTINFORMATION                     = "DATA_CATEGORY_CONTACT_INFORMATION"
	DataCategoryDATACATEGORYFINANCIALINFORMATION                   = "DATA_CATEGORY_FINANCIAL_INFORMATION"
	DataCategoryDATACATEGORYHEALTHINFORMATION                      = "DATA_CATEGORY_HEALTH_INFORMATION"
	DataCategoryDATACATEGORYAUTHENTICATIONCREDENTIALS              = "DATA_CATEGORY_AUTHENTICATION_CREDENTIALS"
	DataCategoryDATACATEGORYBIOMETRICDATA                          = "DATA_CATEGORY_BIOMETRIC_DATA"
	DataCategoryDATACATEGORYLOCATIONDATA                           = "DATA_CATEGORY_LOCATION_DATA"
)
