package models

// EndorsementType represents a endorsement_type
type EndorsementType string

// EndorsementType values
const (
	EndorsementTypeENDORSEMENTTYPEUNSPECIFIED       EndorsementType = "ENDORSEMENT_TYPE_UNSPECIFIED"
	EndorsementTypeENDORSEMENTTYPEBENEFICIARYCHANGE                 = "ENDORSEMENT_TYPE_BENEFICIARY_CHANGE"
	EndorsementTypeENDORSEMENTTYPENOMINEECHANGE                     = "ENDORSEMENT_TYPE_NOMINEE_CHANGE"
	EndorsementTypeENDORSEMENTTYPEADDRESSCHANGE                     = "ENDORSEMENT_TYPE_ADDRESS_CHANGE"
	EndorsementTypeENDORSEMENTTYPECONTACTCHANGE                     = "ENDORSEMENT_TYPE_CONTACT_CHANGE"
	EndorsementTypeENDORSEMENTTYPESUMASSUREDCHANGE                  = "ENDORSEMENT_TYPE_SUM_ASSURED_CHANGE"
	EndorsementTypeENDORSEMENTTYPETERMEXTENSION                     = "ENDORSEMENT_TYPE_TERM_EXTENSION"
	EndorsementTypeENDORSEMENTTYPERIDERADDITION                     = "ENDORSEMENT_TYPE_RIDER_ADDITION"
	EndorsementTypeENDORSEMENTTYPERIDERREMOVAL                      = "ENDORSEMENT_TYPE_RIDER_REMOVAL"
	EndorsementTypeENDORSEMENTTYPEPREMIUMADJUSTMENT                 = "ENDORSEMENT_TYPE_PREMIUM_ADJUSTMENT"
	EndorsementTypeENDORSEMENTTYPECOVERAGECHANGE                    = "ENDORSEMENT_TYPE_COVERAGE_CHANGE"
)
