package models

// KYCStatus represents a kyc_status
type KYCStatus string

// KYCStatus values
const (
	KYCStatusKYCSTATUSUNSPECIFIED KYCStatus = "KYC_STATUS_UNSPECIFIED"
	KYCStatusKYCSTATUSNOTSTARTED            = "KYC_STATUS_NOT_STARTED"
	KYCStatusKYCSTATUSINPROGRESS            = "KYC_STATUS_IN_PROGRESS"
	KYCStatusKYCSTATUSCOMPLETED             = "KYC_STATUS_COMPLETED"
	KYCStatusKYCSTATUSFAILED                = "KYC_STATUS_FAILED"
	KYCStatusKYCSTATUSEXPIRED               = "KYC_STATUS_EXPIRED"
	KYCStatusKYCSTATUSREJECTED              = "KYC_STATUS_REJECTED"
)
