package models

// PartnerType represents a partner_type
type PartnerType string

// PartnerType values
const (
	PartnerTypePARTNERTYPEUNSPECIFIED  PartnerType = "PARTNER_TYPE_UNSPECIFIED"
	PartnerTypePARTNERTYPEHOSPITAL                 = "PARTNER_TYPE_HOSPITAL"
	PartnerTypePARTNERTYPEPHARMACY                 = "PARTNER_TYPE_PHARMACY"
	PartnerTypePARTNERTYPEDOCTOR                   = "PARTNER_TYPE_DOCTOR"
	PartnerTypePARTNERTYPEAMBULANCE                = "PARTNER_TYPE_AMBULANCE"
	PartnerTypePARTNERTYPEAUTOREPAIR               = "PARTNER_TYPE_AUTO_REPAIR"
	PartnerTypePARTNERTYPELAPTOPREPAIR             = "PARTNER_TYPE_LAPTOP_REPAIR"
	PartnerTypePARTNERTYPEMOBILEREPAIR             = "PARTNER_TYPE_MOBILE_REPAIR"
	PartnerTypePARTNERTYPEMFS                      = "PARTNER_TYPE_MFS"
	PartnerTypePARTNERTYPEECOMMERCE                = "PARTNER_TYPE_ECOMMERCE"
	PartnerTypePARTNERTYPEAGENTNETWORK             = "PARTNER_TYPE_AGENT_NETWORK"
	PartnerTypePARTNERTYPECORPORATE                = "PARTNER_TYPE_CORPORATE"
)
