package models

// RefundReason represents a refund_reason
type RefundReason string

// RefundReason values
const (
	RefundReasonREFUNDREASONUNSPECIFIED           RefundReason = "REFUND_REASON_UNSPECIFIED"
	RefundReasonREFUNDREASONFREELOOKCANCELLATION               = "REFUND_REASON_FREE_LOOK_CANCELLATION"
	RefundReasonREFUNDREASONCUSTOMERREQUEST                    = "REFUND_REASON_CUSTOMER_REQUEST"
	RefundReasonREFUNDREASONUNDERWRITINGREJECTION              = "REFUND_REASON_UNDERWRITING_REJECTION"
	RefundReasonREFUNDREASONDUPLICATEPOLICY                    = "REFUND_REASON_DUPLICATE_POLICY"
	RefundReasonREFUNDREASONDEATHOFINSURED                     = "REFUND_REASON_DEATH_OF_INSURED"
	RefundReasonREFUNDREASONPOLICYLAPSED                       = "REFUND_REASON_POLICY_LAPSED"
	RefundReasonREFUNDREASONFRAUD                              = "REFUND_REASON_FRAUD"
)
