package models

// ReportType represents a report_type
type ReportType string

// ReportType values
const (
	ReportTypeREPORTTYPEUNSPECIFIED        ReportType = "REPORT_TYPE_UNSPECIFIED"
	ReportTypeREPORTTYPEDAILYSALES                    = "REPORT_TYPE_DAILY_SALES"
	ReportTypeREPORTTYPEWEEKLYCLAIMS                  = "REPORT_TYPE_WEEKLY_CLAIMS"
	ReportTypeREPORTTYPEMONTHLYREVENUE                = "REPORT_TYPE_MONTHLY_REVENUE"
	ReportTypeREPORTTYPEPARTNERPERFORMANCE            = "REPORT_TYPE_PARTNER_PERFORMANCE"
	ReportTypeREPORTTYPEPRODUCTPERFORMANCE            = "REPORT_TYPE_PRODUCT_PERFORMANCE"
	ReportTypeREPORTTYPECOMPLIANCE                    = "REPORT_TYPE_COMPLIANCE"
)
