package models

// RuleType represents a rule_type
type RuleType string

// RuleType values
const (
	RuleTypeRULETYPEUNSPECIFIED     RuleType = "RULE_TYPE_UNSPECIFIED"
	RuleTypeRULETYPEAGEBASED                 = "RULE_TYPE_AGE_BASED"
	RuleTypeRULETYPELOCATIONBASED            = "RULE_TYPE_LOCATION_BASED"
	RuleTypeRULETYPEOCCUPATIONBASED          = "RULE_TYPE_OCCUPATION_BASED"
	RuleTypeRULETYPEVEHICLETYPE              = "RULE_TYPE_VEHICLE_TYPE"
	RuleTypeRULETYPEHEALTHCONDITION          = "RULE_TYPE_HEALTH_CONDITION"
)
