package models

// RuleCategory represents a rule_category
type RuleCategory string

// RuleCategory values
const (
	RuleCategoryRULECATEGORYUNSPECIFIED        RuleCategory = "RULE_CATEGORY_UNSPECIFIED"
	RuleCategoryRULECATEGORYCLAIMFREQUENCY                  = "RULE_CATEGORY_CLAIM_FREQUENCY"
	RuleCategoryRULECATEGORYDUPLICATECLAIM                  = "RULE_CATEGORY_DUPLICATE_CLAIM"
	RuleCategoryRULECATEGORYSUSPICIOUSTIMING                = "RULE_CATEGORY_SUSPICIOUS_TIMING"
	RuleCategoryRULECATEGORYAMOUNTANOMALY                   = "RULE_CATEGORY_AMOUNT_ANOMALY"
	RuleCategoryRULECATEGORYBENEFICIARYPATTERN              = "RULE_CATEGORY_BENEFICIARY_PATTERN"
	RuleCategoryRULECATEGORYPROVIDERPATTERN                 = "RULE_CATEGORY_PROVIDER_PATTERN"
)
